### ISSUE TITLE
Error using h5readc: The filename specified was either not found... or it contains unsupported characters.

### ISSUE THREAD

**Issue by SamvitJ** [ergysr/DeepCC#17]
This is the next issue I face when trying to install DeepCC, after [this one](https://github.com/ergysr/DeepCC/issues/16). Currently unresolved.

I know this is a Matlab-related problem, but it comes up in the install path for this framework, so I would like to create an issue for the benefit of the offers.

Please let me know you know if you'd prefer I not do so. Please also let me know the fix if you have encountered this problem as well.

```
>> run demo.m

The MATLAB interface for Gurobi 8.0.0 has been installed.

The directory
    /opt/gurobi800/linux64/matlab/
has been added to the MATLAB path.
To use Gurobi regularly, you must save this new path definition.
To do this, type the command
    savepath
at the MATLAB prompt. Please consult the MATLAB documentation
if necessary.

Error using h5readc
The filename specified was either not found on the MATLAB path or it
contains unsupported characters.

Error in h5read (line 58)
[data,var_class] = h5readc(Filename,Dataset,start,count,stride);

Error in compute_L1_tracklets (line 16)
    features   =
    h5read(sprintf('%s/%s/L0-features/features%d.h5',opts.experiment_root,opts.experiment_name,iCam),'/emb');
    
Error in demo (line 18)
compute_L1_tracklets(opts);

Error in run (line 91)
evalin('caller', strcat(script, ';'));
```

**Comment by ergysr** [comment]
There could be few reasons, although I haven't encountered this before.

1. Corrupt .h5 feature file after download. (not likely) 
2. Incompatible version of the HDF5 library. I don't remember which version I used when generating the OpenPose .h5 features, probably `1.8.16`, but I suspect your version might be slightly older can't parse the newer format. Can you run `dpkg -l | grep hdf5`? Maybe all you need to do is upgrade HDF5.
3. Or this [issue](https://www.mathworks.com/matlabcentral/answers/388957-hdf5-v1-10), so make sure you are not using `1.10.0` or newer because Matlab 2017 and beyond can't support it.

**Comment by chunniunai220ml** [comment]
@SamvitJ  Have you solved the problem with ergysr's answers?
Now, I have the same problem  in matlab2015b without Gurobi,win7. Can you share your solution with me?
