### ISSUE TITLE
Found dupicate ID/Frame pairs.

### ISSUE THREAD

**Issue by lonelylingoes** [ergysr/DeepCC#30]
When running "compute_L3_identities()", the exception "Found dupicate ID/Frame pairs"  comes out.
And I set the "opts.optimization = 'KL' ".

**Comment by ergysr** [comment]
The KL solver might not respect all hard constraints if this happens. It is probably an implementation issue which goes beyond the scope of this work. I used BIPCC which doesn't have this issue.

One thing that could help is setting all -inf correlations to -1000 before calling KL, as it might give the solver numerical stability. Otherwise you could fall back to BIPCC when the error happens.

**Comment by lonelylingoes** [comment]
Thanks for you reply.
 I use 'AL-ICM',  it works ok.  And I set all -inf correlations to -1000 before calling KL, it sometimes works ok, sometimes not.

**Comment by ergysr** [comment]
I am closing this issue as it is not directly an issue of DeepCC. You might check in the [KL repository](https://github.com/bjoern-andres/graph) for a solution.
