### ISSUE TITLE
Run at lower frame sampling rate

### ISSUE THREAD

**Issue by SamvitJ** [ergysr/DeepCC#35]
Is it possible to run a DeepCC on a smaller subset of the frames of the Duke dataset? For example, using every 10th frame from each camera, instead of every single frame.

Also (not sure if this is a problem): I noticed the MTMC tracker outputs ~1 million detections right now, but there are ~4 million labelled detections in the ground truth file. Why is there a gap here? (Does the framework already operate at a sampling rate of 1/4 frames?)

**Comment by ergysr** [comment]
DeepCC operates at 60 fps temporal resolution. In the past I have done experiments at 30 fps for BIPCC, and interpolating the trajectories to 60 fps resulted in essentially no difference in scores. You would need to sample frames with your own logic as such sampling was not the focus of this repo.

I am not sure I understand the second issue. A 4x gap seems extremely large, and would likely result in a low IDF1 score when you run the demo. Perhaps you are looking at the output for trainval-mini, while the ground truth is provided for the entire trainval.

**Comment by SamvitJ** [comment]
Yes, I am looking at trainval_mini! That is located under experiments/demo/L3-identities. Are the full inference outputs available somewhere else? (The README seems to indicate mini is the full output.)

Also what subset of the data does "mini" cover? I'm looking at http://vision.cs.duke.edu/DukeMTMC/details.html, and it describes trainval, test-easy, and test-hard, but no trainval-mini.

**Comment by SamvitJ** [comment]
With regards to the sampling rate, I am not trying to modify the operation of the DeepCC tracker, but instead building a model that runs on top of its output. As the last experiment in a paper that I'm writing (due Thursday!), I'm trying to understand the tradeoff between the density of the tracker's output, and the accuracy of *my* model.

Do you have any hints on where I could modify your code to adjust the sampling rate? Or else if you still have the script from your experiments, could you send it to me? Email is samvit@eecs.berkeley.edu. I really appreciate it!

**Comment by ergysr** [comment]
Here is the [frame intervals](https://github.com/ergysr/DeepCC/blob/master/get_opts.m#L27-L28). trainval-mini is a small subset of trainval for faster prototyping/evaluation.

Wouldn't it be enough to sample the final output of DeepCC every k frames for your purposes? In that case it would be straightforward to extract the data from the inference outputs in the L3 folder. 

If you instead need to re-run the tracker at different fps, this would require some additional effort.

**Comment by SamvitJ** [comment]
Ergys: thanks for the pointer to the frame intervals!

And good point! I realized that as well, and I am running an experiment right now where I sample the output every 60 frames. However, the property that I'm trying to investigate is the trade-off between labelling *compute time*, and subsequent accuracy. If we just sample the final output, we still had to spend the time labelling the full data.

If running the tracker at different fps is tricky, another possibility would be to run the tracker on a smaller subset of the data, by adjusting the frame intervals, as you did. Are there any gotchas here? Thanks in advance.

And thanks for your suggestions/feedback in general!

**Comment by ergysr** [comment]
I'm not very clear what you mean by "labeling compute time, and subsequently accuracy". Are you referring to the compute time of the graph labeling algorithms like AL-ICM or KL? 

If you sample the final output every 60 frames but you don't find this approach satisfactory for some reason, then running the tracker on a smaller subset of data would have issues for the exact same reason.

On another note, modifying the framerate generally affects only tracklet computation (L1). If you still interpolate tracklets to be 1-second long, then computing single- and multi-camera trajectories (L2 and L3) would have roughly the same run-time as the number of tracklets would be similar. In this approach you can start by changing [this line](https://github.com/ergysr/DeepCC/blob/ab89f0a82a6b603d87c508b2c3ddc217d7075d6e/src/compute_L1_tracklets.m#L34) so that in each 1-second window you are sampling fewer detections.
