### ISSUE TITLE
Without Gurobi, is BIPCC used?

### ISSUE THREAD

**Issue by NicksonYap** [ergysr/DeepCC#63]
Hi @ergysr,

BIPCC seems to be one of the core reasons DeepCC works well

If without using Gurobi and BIPCC is not used, would DeepCC perform neglegibly just as well?
Or would therw be an obvious performance impact?

Regards

**Comment by ergysr** [comment]
@NicksonYap, there is no good answer to this, which makes it an interesting research question. 

On one hand an optimal solver like BIPCC is quite useful when the features are noisy. If the features were perfect, greedy matching would also work. On the other hand, at least for this code, plugging in the KL solver is OK for tracklets, but negatively affects performance for single- and multi-camera tracking because KL has no accuracy guarantees, so BIPCC is the default.

There is [other work](https://arxiv.org/abs/1712.09531) that uses simpler hierarchical clustering with strong features and does equally well. This suggests that with a more careful implementation good performance is also possible. Currently I'm not aware of a systematic study about the role of optimization in MTMCT.
