### ISSUE TITLE
Literature on L1 tracklets motion affinity computation.

### ISSUE THREAD

**Issue by Sukanya-Kudi** [ergysr/DeepCC#65]
Could you suggest reading material for the motion affinity estimation as in the error forward, backward. And why it is useful/robust.

**Comment by ergysr** [comment]
Reasoning both forward and backward in time gives two measurements instead of one, which can increase estimation robustness.

Each motion model type has its own trade-offs, and here you can find few:
- The IoU Tracker (Bochinski et al) works well if detections are high quality and the frame-rate is high.
- A constant velocity motion model (this repository) assumes objects move at constant speeds, which is reasonable for pedestrians at typical video framerates, but this model fails with abrupt changes of direction or volatile speeds. 
- A linear motion model can be made more general by assuming higher-order motion models (Robert Collins), e.g. constant acceleration. 
- You one can model motion with smooth trajectories (Discrete Continuous Multi-Target Tracking by Anton Milan).
- On another category you'll find papers that try to learn non-linear motion models (Yang & Nevatia), or enforce local connectivity in the detections (Lifted Multicuts by Tang et al).
