### ISSUE TITLE
about the mexopencv version

### ISSUE THREAD

**Issue by MOONBEAR0703** [ergysr/DeepCC#8]
@ergysr hi, I have tried to install mexopencv with opencv 3.2, but failed many times.So could you tell me your opencv version? I am in linux system,my matlab is R2016b,my opencv is 3.2.

**Comment by ergysr** [comment]
I use OpenCV 3.3, R2017b, Windows10, VS2015 compiler. You might want to check the [mexOpenCV 3.2 branch](https://github.com/kyamagu/mexopencv/tree/v3.2.0).

**Comment by MOONBEAR0703** [comment]
Thanks, so you make the process in the windows to extract frames? With a cpu?

**Comment by ergysr** [comment]
I use a windows machine with a gpu. I don't extract the frames because they take space, instead the code reads the frames directly from the videos using mexopencv. 

If for some reason you cannot compile mexopencv, you can extract all the video frames using ffmpeg. Then you can use [DukeFrameReader](https://github.com/ergysr/DeepCC/blob/master/src/duke/DukeFrameReader.m) instead of [DukeVideoReader](https://github.com/ergysr/DeepCC/blob/master/src/duke/DukeVideoReader.m).

**Comment by MOONBEAR0703** [comment]
I finally found that it was the wrong mexopencv that made me fail. Because the git clone link it provided was always the mexopencv-3-4  even though I turned to the mexopencv-3-2 branch.
